# Generated by Django 3.1.7 on 2021-04-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_shopuserprofile_vk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='vk_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='id ВКонтакте'),
        ),
    ]
